language: go
sudo: required
dist: xenial

go:
  - 1.12.x

os:
  - linux-ppc64le

go_import_path: github.com/kubernetes-sigs/cri-tools

services:
  - docker

before_install:
  - |
    (
      set -Eeuo pipefail
      if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        choco install -y make mingw
        export PATH="/c/tools/mingw64/bin:/c/ProgramData/chocolatey/bin;$PATH"
      fi
    )

install:
  - make install.tools

jobs:
  include:
    - stage: Test
      os: linux-ppc64le
      script:
        - make
        - travis_wait bash -x hack/install-docker.sh
        - travis_wait bash -x hack/install-kubelet.sh
        - sudo env PATH=$PATH GOPATH=$GOPATH bash -x hack/run-critest.sh

stages:
  - Test
